/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package no.vegvesen.tk.akf.akf_petstore_api.models.operations;

import java.net.http.HttpResponse;

public class AddPetResponse {
    
    public String contentType;
    public AddPetResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * unexpected error
     */
    
    public no.vegvesen.tk.akf.akf_petstore_api.models.shared.Error error;
    public AddPetResponse withError(no.vegvesen.tk.akf.akf_petstore_api.models.shared.Error error) {
        this.error = error;
        return this;
    }
    
    /**
     * pet response
     */
    
    public no.vegvesen.tk.akf.akf_petstore_api.models.shared.Pet pet;
    public AddPetResponse withPet(no.vegvesen.tk.akf.akf_petstore_api.models.shared.Pet pet) {
        this.pet = pet;
        return this;
    }
    
    
    public Integer statusCode;
    public AddPetResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public AddPetResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
}
