/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package no.vegvesen.tk.akf.akf_petstore_api;

import no.vegvesen.tk.akf.akf_petstore_api.utils.HTTPClient;

class SDKConfiguration {
	public HTTPClient defaultClient;
	public HTTPClient securityClient;
	
	public String serverUrl;
	public int serverIdx = 0;
	public String language = "java";
	public String openapiDocVersion = "1.0.0";
	public String sdkVersion = "1.17.0";
	public String genVersion = "2.39.0";
	
}