/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package no.vegvesen.tk.akf.akf_petstore_api.utils;

import java.net.http.HttpRequest.BodyPublisher;

public class SerializedBody {
    public String contentType;
    public BodyPublisher body;
}
